# Generated by Django 5.0.dev20230124092027 on 2023-03-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = []
