# Generated by Django 5.0.dev20230124092027 on 2023-03-02 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_auto_20230302_1900"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendrequest",
            unique_together={("from_user", "to_user")},
        ),
        migrations.AddField(
            model_name="friendrequest",
            name="to_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friend_requests_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="from_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friend_requests_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="friendrequest",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="friendrequest",
            name="sender",
        ),
    ]
