# Generated by Django 5.0.dev20230124092027 on 2023-03-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_friendrequest_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="friendrequest",
            old_name="accepted",
            new_name="is_accepted",
        ),
    ]
