# Generated by Django 5.0.dev20230124092027 on 2023-03-02 19:11

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_accepted_friendrequest_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='to_user',
            field=models.ForeignKey(on_delete=models.CASCADE, to='users.User'),
        ),
    ]
