# Generated by Django 5.0.dev20230124092027 on 2023-03-02 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0006_auto_20230302_1912"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendrequest",
            name="to_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friend_requests_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
