# Generated by Django 5.0.dev20230124092027 on 2023-03-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prof", "0002_remove_userprofile_avatar_remove_userprofile_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
