# Generated by Django 4.1.7 on 2023-03-21 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0004_initial"),
        ("prof", "0004_remove_friendrequest_created_at_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="UserProf",
        ),
        migrations.AlterUniqueTogether(
            name="friendrequest",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_user",
                to="accounts.user",
            ),
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_user",
                to="accounts.user",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="friends",
            field=models.ManyToManyField(
                blank=True, related_name="friends", to="accounts.user"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.user"
            ),
        ),
        migrations.RemoveField(
            model_name="friendrequest",
            name="is_accepted",
        ),
    ]
