# Generated by Django 5.0.dev20230124092027 on 2023-03-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_is_active_user_is_admin_user_last_login_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
