# Generated by Django 4.1.7 on 2023-03-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0002_remove_score_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="privacy",
            field=models.BooleanField(default=True),
        ),
    ]
