# Generated by Django 4.1.7 on 2023-03-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('answer_a', models.CharField(max_length=200)),
                ('answer_b', models.CharField(max_length=200)),
                ('answer_c', models.CharField(max_length=200)),
                ('answer_d', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=1)),
            ],
        ),
    ]
